# Generated by Django 4.1.1 on 2022-09-23 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_salud',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_de_salud', to=settings.AUTH_USER_MODEL),
        ),
    ]
